module.exports = {
    httpUnsafeOrigin: 'http://docs.mule.net:8094',
    httpSafeOrigin: "http://docs.mule.net:8094",
    httpAddress: '0.0.0.0',
    httpPort: 3000,
    websocketPort: 3003,
    maxWorkers: 2,
    adminKeys: [],
    filePath: './datastore/',
    archivePath: './data/archive',
    pinPath: './data/pins',
    taskPath: './data/tasks',
    blockPath: './block',
    blobPath: './blob',
    blobStagingPath: './data/blobstage',
    decreePath: './data/decrees',
    logPath: './data/logs',
    logToStdout: true,
    logLevel: 'info',
    verbose: false,
    installMethod: 'docker',
    defaultStorageLimit: 150 * 1024 * 1024,
};
